let bosses = [
    {id:1, nombre:"Abyssador", cantidad: 60, tipo: "Archfoe", img:"../img/imgbosstiary/Abyssador.gif",localizacion:"Gnome Base"},
    {id:2, nombre:"Alptramun", cantidad: 5, tipo: "Nemesis",img:"../img/imgbosstiary/Alptramun.gif",localizacion:"Dream Scar"},
    {id:3, nombre:"Amenef The Burning", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Amenef_The_Burning.gif",localizacion:"Kilmaresh"},
    {id:4, nombre:"Anomaly", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Anomaly.gif",localizacion:"The Void"},
    {id:5, nombre:"Black Vixen", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Black_Vixen.gif",localizacion:"Grimvale"},
    {id:6, nombre:"Bloodback", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Bloodback.gif",localizacion:"Grimvale"},
    {id:7, nombre:"Bragrumol", cantidad: 300, tipo:  "Bane",img:"../img/imgbosstiary/Bragrumol.gif",localizacion:"Kilmaresh"},
    {id:8, nombre:"Brokul", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Brokul.gif",localizacion:"Ancient Ancestorial Grounds"},
    {id:9, nombre:"Chikhaton", cantidad: 5, tipo:  "Nemesis",img:"../img/imgbosstiary/Chikhaton.gif",localizacion:"Edron"},
    {id:10, nombre:"Count Vlarkorth", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Count_Vlarkorth.gif",localizacion:"Edron"},
    {id:11, nombre:"Darkfang", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Darkfang.gif",localizacion:"Grimvale"},
    {id:12, nombre:"Dazed Leaf Golem", cantidad: 300, tipo:  "Bane",img:"../img/imgbosstiary/Dazed_Leaf_Golem.gif",localizacion:"Falcon Bastion"},
    {id:13, nombre:"Deathstrike", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Deathstrike.gif",localizacion:"Gnome Base"},
    {id:14, nombre:"Dipthrah", cantidad: 300, tipo:  "Bane",img:"../img/imgbosstiary/Dipthrah.gif",localizacion:"Ankrahmun Pharaoh Tombs (Mountain)"},
    {id:15, nombre:"Drume", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Drume.gif",localizacion:"Bounac"},
    {id:16, nombre:"Duke Krule", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Duke_Krule.gif",localizacion:"Thais"},
    {id:17, nombre:"Earl Osam", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Earl_Osam.gif",localizacion:"Cormaya"},
    {id:18, nombre:"Enusat The Onyx Wing", cantidad: 300, tipo:  "Bane",img:"../img/imgbosstiary/Enusat_The_Onyx_Wing.gif",localizacion:"Kilmaresh"},
    {id:19, nombre:"Eradicator", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Eradicator.gif",localizacion:"The Void"},
    {id:20, nombre:"Faceless Bane", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Faceless_Bane.gif",localizacion:"Buried Cathedral"},
    {id:21, nombre:"Gaffir", cantidad: 300, tipo:  "Bane",img:"../img/imgbosstiary/Gaffir.gif",localizacion:"Cobra Bastion"},
    {id:22, nombre:"Gaz'haragoth", cantidad: 5, tipo:  "Nemesis",img:"../img/imgbosstiary/Gaz'haragoth.gif",localizacion:"Prison"},
    {id:23, nombre:"Glitterscale", cantidad: 300, tipo:  "Bane",img:"../img/imgbosstiary/Glitterscale.gif",localizacion:"Ancient Temple"},
    {id:24, nombre:"Gnomevil", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Gnomevil.gif",localizacion:"Gnome Base"},
    {id:25, nombre:"Grand Commander Soeren", cantidad: 300, tipo:  "Bane",img:"../img/imgbosstiary/Grand_Commander_Soeren.gif",localizacion:"Falcon Bastion"},
    {id:26, nombre:"Grand Master Oberon", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Grand_Master_Oberon.gif",localizacion:"Falcon Bastion"},
    {id:27, nombre:"Guard Captain Quaid", cantidad: 300, tipo:  "Bane",img:"../img/imgbosstiary/Guard_Captain_Quaid.gif",localizacion:"Cobra Bastion"},
    {id:28, nombre:"Heoni", cantidad: 300, tipo:  "Bane",img:"../img/imgbosstiary/Abyssador.gif",localizacion:"Edron Mountain"},
    {id:29, nombre:"Irgix The Flimsy", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Heoni.gif",localizacion:"Port Hope"},
    {id:30, nombre:"Izcandar the Banished", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Izcandar_the_Banished.gif",localizacion:"Dream Scar"},
    {id:31, nombre:"Jailer", cantidad: 300, tipo:  "Bane",img:"../img/imgbosstiary/Jailer.gif",localizacion:"Falcon Bastion"},
    {id:32, nombre:"Katex Blood Tongue", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Katex_Blood_Tongue.gif",localizacion:"Lion Sanctum"},
    {id:33, nombre:"Kroazur", cantidad: 300, tipo:  "Bane",img:"../img/imgbosstiary/Kroazur.gif",localizacion:"Feyrist Nightmare"},
    {id:34, nombre:"Kusuma", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Kusuma.gif",localizacion:"Stardance Mountains"},
    {id:35, nombre:"Lady Tenebris", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Lady_Tenebris.gif",localizacion:"Black Sphinx Estate"},
    {id:36, nombre:"Lord Azaram", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Lord_Azaram.gif",localizacion:"Carlin"},
    {id:37, nombre:"Lord Retro", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Lord_Retro.gif",localizacion:"Temporal Tides."},
    {id:38, nombre:"Malofur Mangrinder", cantidad: 5, tipo:  "Nemesis",img:"../img/imgbosstiary/Malofur_Mangrinder.gif",localizacion:"Dream Scar"},
    {id:39, nombre:"Maxxenius", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Maxxenius.gif",localizacion:"Dream Scar"},
    {id:40, nombre:"Megasylvan Yselda", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Megasylvan_Yselda.gif",localizacion:"Bounac"},
    {id:41, nombre:"Mozradek", cantidad: 300, tipo:  "Bane",img:"../img/imgbosstiary/Mozradek.gif",localizacion:"Kilmaresh"},
    {id:42, nombre:"Neferi The Spy", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Neferi_The_Spy.gif",localizacion:"Kilmaresh"},
    {id:43, nombre:"Outburst", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Outburst.gif",localizacion:"The Void"},
    {id:44, nombre:"Phrodomo", cantidad: 5, tipo:  "Nemesis",img:"../img/imgbosstiary/Phrodomo.gif",localizacion:"Ghostlands Carlin"},
    {id:45, nombre:"Plagueroot", cantidad: 5, tipo:  "Nemesis",img:"../img/imgbosstiary/Plagueroot.gif",localizacion:"Dream Scar"},
    {id:46, nombre:"Preceptor Lazare", cantidad: 300, tipo:  "Bane",img:"../img/imgbosstiary/Preceptor_Lazare.gif",localizacion:"Falcon Bastion"},
    {id:47, nombre:"Rahemos", cantidad: 300, tipo:  "Bane",img:"../img/imgbosstiary/Rahemos.gif",localizacion:"Ankrahmun Pharaoh Tombs (Oasis)"},
    {id:48, nombre:"Ratmiral Blackwhiskers", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Ratmiral_Blackwhiskers.gif",localizacion:"The Wreckoning"},
    {id:49, nombre:"Ravenous Hunger", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Ravenous_Hunger.gif",localizacion:"Cults of Tibia (The Barkless)"},
    {id:50, nombre:"Raxias", cantidad: 5, tipo:  "Nemesis",img:"../img/imgbosstiary/Raxias.gif",localizacion:"Feyrist"},
    {id:51, nombre:"Realityquake", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Realityquake.gif",localizacion:"The Void"},
    {id:52, nombre:"Rupture", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Rupture.gif",localizacion:"The Void"},
    {id:53, nombre:"Scarlett Etzel", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Scarlett_Etzel.gif",localizacion:"Cobra Bastion"},
    {id:54, nombre:"Shadowpelt", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Shadowpelt.gif",localizacion:"Grimvale"},
    {id:55, nombre:"Sharpclaw", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Sharpclaw.gif",localizacion:"Grimvale"},
    {id:56, nombre:"Sir Baeloc", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Sir_Baeloc.gif",localizacion:"Darashia"},
    {id:57, nombre:"Sir Nictros", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Sir_Nictros.gif",localizacion:"Darashia"},
    {id:58, nombre:"Sister Hetai", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Sister_Hetai.gif",localizacion:"Kilmaresh"},
    {id:59, nombre:"Srezz Yellow Eyes", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Srezz_Yellow_Eyes.gif",localizacion:"Lion Sanctum"},
    {id:60, nombre:"Tentugly", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Tentugly's_Head.gif",localizacion:"Rascacoon."},
    {id:61, nombre:"Thaian", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Thaian.gif",localizacion:"Edron"},
    {id:62, nombre:"The Count of the Core", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/The_Count_of_the_Core.gif",localizacion:"War Zone 5"},
    {id:63, nombre:"The Dread Maiden", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/The_Dread_Maiden.gif",localizacion:"Zarganash"},
    {id:64, nombre:"The Enraged Thorn Knight", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/The_Enraged_Thorn_Knight.gif",localizacion:"Desecrated Glade"},
    {id:65, nombre:"The Fear Feaster", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/The_Fear_Feaster.gif",localizacion:"Zarganash"},
    {id:66, nombre:"The Flaming Orchid", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/The_Flaming_Orchid.gif",localizacion:"Asura Palace"},
    {id:67, nombre:"The Moonlight Aster", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/The_Moonlight_Aster.gif",localizacion:"Asura Palace"},
    {id:68, nombre:"The Nightmare Beast", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/The_Nightmare_Beast.gif",localizacion:"Dream Scar"},
    {id:69, nombre:"The Pale Worm", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/The_Pale_Worm.gif",localizacion:"Zarganash"},
    {id:70, nombre:"The Unwelcome", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/The_Unwelcome.gif",localizacion:"Zarganash"},
    {id:71, nombre:"The Winter Bloom", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/The_Winter_Bloom.gif",localizacion:"Asura Palace"},
    {id:72, nombre:"Timira The Many-Headed", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Timira_The_Many-Headed.gif",localizacion:"Emerald Gardens"},
    {id:73, nombre:"Unaz The Mean", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Unaz_The_Mean.gif",localizacion:"Port Hope"},
    {id:74, nombre:"Urmahlullu The Weakened", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Urmahlullu_The_Weakened.gif",localizacion:"Kilmaresh"},
    {id:75, nombre:"Utua Stone Sting", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Utua_Stone_Sting.gif",localizacion:"Lion Sanctum"},
    {id:76, nombre:"Vashresamun", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Vashresamun.gif",localizacion:"Ankrahmun Pharaoh Tombs (Ancient Ruins)"},
    {id:77, nombre:"Vok The Freakish", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Vok_The_Freakish.gif",localizacion:"Port Hope"},
    {id:78, nombre:"Xogixath", cantidad: 300, tipo:  "Bane",img:"../img/imgbosstiary/Xogixath.gif",localizacion:"Kilmaresh"},
    {id:79, nombre:"Yirkas Blue Scales", cantidad: 60, tipo:  "Archfoe",img:"../img/imgbosstiary/Yirkas_Blue_Scales.gif",localizacion:"Lion Sanctum"},


    
]